---
variables:
  GITLAB_ENV: development

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      variables:
        GITLAB_ENV: production
    - when: always

stages:
  - deploy
  - mirror

deploy-job:
  stage: deploy
  environment: $GITLAB_ENV
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws s3 sync --delete --acl public-read --exclude "*" --include "*/assets/*" --exclude "*/.gitkeep" recipes s3://${HPCDK_S3_BUCKET}/${CI_COMMIT_BRANCH}/recipes/

mirror-to-github:
  stage: mirror
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apk add --no-cache git
    - git config --global user.email "hpc-dr@amazon.com"
    - git config --global user.name "GitLab CI - HPC Developer Relations"
  script:
    - echo "Token prefix: ${GITHUB_ACCESS_TOKEN:0:4}..."
    - git clone --mirror $CI_REPOSITORY_URL repo
    - cd repo
    - git push --mirror https://oauth2:${GITHUB_ACCESS_TOKEN}@github.com/aws-samples/aws-hpc-recipes.git
