variables:
  GITLAB_ENV: development

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      variables:
        GITLAB_ENV: production
    - when: always

stages:
  - deploy
  - mirror

deploy-job:
  stage: deploy  
  environment: $GITLAB_ENV
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws s3 sync --delete --acl public-read --exclude "*" --include "*/assets/*" --exclude "*/.gitkeep" recipes s3://${HPCDK_S3_BUCKET}/${CI_COMMIT_BRANCH}/recipes/

mirror-to-github:
  stage: mirror
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apk add --no-cache git openssh-client
    - eval $(ssh-agent -s)
    - echo "${GITHUB_SSH_PRIVATE_KEY}" | tr -d '\r' | sed -e 's/^[ \t]*//' | sed -e 's/[ \t]*$//' > private_key.pem
    - chmod 600 private_key.pem
    - ssh-keygen -p -f private_key.pem -m pem -P "" -N ""
    - ssh-add private_key.pem
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "hpc-dr@amazon.com"
    - git config --global user.name "GitLab CI - AWS HPC Developer Relations"
  script:
    - git clone --single-branch --branch main $CI_REPOSITORY_URL repo
    - cd repo
    - git push --force git@github.com:aws-samples/aws-hpc-recipes.git main:main
  retry: 2
  after_script:
    - rm -f private_key.pem
  