AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Component to run OS updates when building PCS-compatible AMIs

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: HPC Recipes Configuration
        Parameters:
          - HpcRecipesS3Bucket
          - HpcRecipesBranch

Parameters:
  HpcRecipesS3Bucket:
    Type: String
    Default: aws-hpc-recipes
    Description: HPC Recipes for AWS S3 bucket
    AllowedValues:
         - aws-hpc-recipes
         - aws-hpc-recipes-dev
  HpcRecipesBranch:
    Type: String
    Default: main
    Description: HPC Recipes for AWS release branch
    AllowedPattern: '^(?!.*/\.git$)(?!.*/\.)(?!.*\\.\.)[a-zA-Z0-9-_\.]+$'

Resources:
  UpdateOs:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'UpdateOs-${AWS::StackName}'
      Description: Downgrade kernel to address compatibility issues
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'Downgrade kernel for PCS AMI'
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: DownloadCommon
                action: WebDownload
                inputs:
                  - source: https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/common.sh
                    destination: common.sh
              - name: DownloadUpdateScript
                action: WebDownload
                inputs:
                  - source: https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/downgrade-kernel.sh
                    destination: downgrade-kernel.sh
              - name: ExecuteUpdateScript
                action: ExecuteBash
                inputs:
                  commands:
                    - set -e
                    - 'chmod +x downgrade-kernel.sh'
                    - './downgrade-kernel.sh'

Outputs:
  ImageBuilderComponent:
    Value: !Ref UpdateOs
