AWSTemplateFormatVersion: 2010-09-09
Description: Minimal EC2 launch template for an AWS PCS compute node group.
  This template creates a minimal EC2 launch template for AWS PCS compute node groups.
  It demonstrates how to configure EC2 instance tags, IMDSv2, and the cluster security group needed to communicate with the AWS PCS controller.
  You can use it as a starting point for creating a custom launch template to meet your specific needs.
  Check the Outputs tab of this stack for useful details about resources created by this template.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Security
        Parameters:
          - ClusterSecurityGroupId

Parameters:

  ClusterSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for PCS cluster controller and nodes.

Resources:

  ComputeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub 'simple-compute-${AWS::StackName}'
      # Tag so we know this came from HPC Recipes
      LaunchTemplateData:
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: HPCRecipes
                Value: "true"
        # Require IMDS v2
        MetadataOptions:
          HttpEndpoint: enabled
          HttpPutResponseHopLimit: 4
          HttpTokens: required
        # Include cluster security group
        SecurityGroupIds:
          - !Ref ClusterSecurityGroupId


Outputs:
  ComputeLaunchTemplateName:
    Description: "Node group template name"
    Value: !Sub 'simple-compute-${AWS::StackName}'
  ComputeLaunchTemplateId:
    Description: "Node group template ID"
    Value: !Ref ComputeLaunchTemplate
